name: MyHouse CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Deployment started at $(date)"
            mkdir -p ~/app 
            cd ~/app

            echo "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}" > .env
            export DOCKER_IMAGE=$(grep DOCKER_IMAGE .env | cut -d '=' -f2)
            sudo chown -R ubuntu:ubuntu ~/app
            
            echo "==== Debugging: Content of .env file ===="
            cat .env
            echo "========================================="
                        
            echo "==== Debugging: Content of docker-compose.yml ===="
            cat docker-compose.yml
            echo "=================================================="
            
            echo "==== Debugging: Docker Compose config ===="
            docker-compose --env-file .env config
            echo "=========================================="
            
            echo "docker-compose --env-file .env down start"
            docker-compose --env-file .env down
            echo "docker-compose --env-file .env down end"
            
            echo "docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} start"
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            echo "docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} end"
            
            echo "docker-compose --env-file .env up -d start"
            docker-compose --env-file .env up -d
            echo "docker-compose --env-file .env up -d end"
            
            docker image prune -af
            echo "Deployment completed at $(date)"